cv_mode: loso
shared:
  data_sources:
    milestone2:
      path: ./combined_data_S008.h5
      prefix: m2_
      exclude_subjects: []
  subjects:
  - m2_S001
  - m2_S002
  - m2_S003
  - m2_S004
  - m2_S005
  - m2_S006
  - m2_S007
  - m2_S008
  conditions:
  - level_075mps
  - level_100mps
  - level_125mps
  - accel_sine
  - decline_5deg
  - incline_10deg
  - stopandgo
  input_vars:
  - - derived/body_frame_imu
    - - accel_right
      - accel_forward
      - accel_up
      - gyro_right
      - gyro_forward
      - gyro_up
      - forward_accel_overground
  - - robot/left
    - - hip_angle
      - thigh_angle
      - torque
  - - robot/right
    - - hip_angle
      - thigh_angle
      - torque
  - - derived/model_com_speed_nogrf
    - - model_com_speed_nogrf_kin
  - - sub_info
    - - height
      - weight
  output_vars:
  - - common
    - - v_Y_true
  lpf_cutoff: 0.5
  lpf_order: 4
  data:
    window_size: 300
    stride: 5
    stride_inf: 1
    y_delay: 5
    est_tick_ranges:
    - 5
    normalize: true
    time_window_output: 1
  model:
    type: TCN_GRU
    gru_hidden: 24
    channels:
    - 24
    - 24
    - 48
    - 48
    - 64
    - 64
    kernel_size: 5
    dropout: 0.2
    head_hidden:
    - 48
    head_dropout: 0.4
    model_norm: batch
    use_input_norm: true
    input_norm_type: instance
    ar_feedback:
      enable: false
    use_norm: true
  input_lpf_per_group:
    accelerations: 8.0
    imu: 8.0
    velocities: 4.0
02_train:
  data:
    window_size: 300
    stride: 5
    stride_inf: 1
    y_delay: 5
    est_tick_ranges:
    - 5
    normalize: true
    time_window_output: 1
    normalize_type: standard
    use_physical_velocity_model: false
    use_gait_phase: false
    input_lpf_per_group:
      accelerations: 8.0
      imu: 8.0
      velocities: 4.0
  model:
    type: TCN_GRU
    gru_hidden: 24
    channels:
    - 24
    - 24
    - 48
    - 48
    - 64
    - 64
    kernel_size: 5
    dropout: 0.2
    head_hidden:
    - 48
    head_dropout: 0.4
    model_norm: batch
    use_input_norm: true
    input_norm_type: instance
    ar_feedback:
      enable: false
    use_norm: true
  loader:
    batch_size: 128
    val_batch_size: 256
  train:
    task_type: regression
    loss: huber
    huber_delta: 0.1
    epochs: 30
    lr: 0.001
    wd: 0.001
    amp: true
    device: cuda
    save_dir: ./runs_tcn
    early_stop_patience: 10
    early_stop_min_delta: 0.0001
    early_stop_warmup: 10
    k_fold: 4
    cos_T0: 10
    cos_Tmult: 1
    eta_min: 1.0e-05
    augment_noise_std: 0.03
    smoothness_loss_weight: 0.0
    kinematic_loss_weight_pos: 0.0
    kinematic_loss_weight_limit: 0
    kinematic_loss_degrees: false
    kinematic_loss_tolerance: 0.05
    train_loss_target: 0.0
03_eval:
  split:
    mode: loso
    level: subject
    seed: 42
    ratio:
    - 0.7
    - 0.15
    - 0.15
    manual:
      val:
      - m2_S007
      test:
      - m2_S008
    save_to: null
    loso_subjects:
    - m2_S008
  data:
    window_size: 300
    stride: 5
    stride_inf: 1
    y_delay: 5
    est_tick_ranges:
    - 5
    normalize: true
    time_window_output: 1
  train:
    device: cuda
  scaler_path: ./runs_tcn/scaler.npz
exp_name: exp_WG_S1A1_bf_modelcom_kin_w300_compact_pglpf
