/**
 * @file  version.h
 * @author Angel Robotics
 * @brief  Application firmware version definition
 * @details
 *   Auto-generated by version_generator.py from git tag (vMAJOR.MINOR.PATCH.DEBUG).
 *   Manual editing is allowed but version_generator.py will overwrite on next run.
 *   Each field must be 0-255 (uint8_t) to fit AGR_FwInfo_t and packaged.bin header.
 * @copyright Copyright (c) Angel Robotics Inc.
 */

#ifndef XM_FW_SYSTEM_CONFIG_VERSION_H_
#define XM_FW_SYSTEM_CONFIG_VERSION_H_

#define FW_VER_MAJOR    1
#define FW_VER_MINOR    0
#define FW_VER_PATCH    0
#define FW_VER_DEBUG    0

#endif /* XM_FW_SYSTEM_CONFIG_VERSION_H_ */
